# Generated by Django 5.1.7 on 2025-05-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_order_itemorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ItemOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
